# This is a just working test

language: scala

script:
  - sbt "runMain Main" # Working test

# To avoid `java.awt.HeadlessException`
# (from: https://jnorthr.wordpress.com/tag/java-awt-headlessexception/)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


# (from: http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete


# (from: http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
