# This is a just working test

language: scala

script:
  - sbt run

# To avoid `java.awt.HeadlessException`
# (from: https://jnorthr.wordpress.com/tag/java-awt-headlessexception/)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"